version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 39875:39875
      - 39876:39876
      - 39876:39876/udp
      - 39878:39878
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r rustdesk.example.com:39877
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 39877:39877
      - 39879:39879
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
