name: test

on:
  workflow_dispatch:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: deep-soft/checkout@v3
      - uses: deep-soft/rust-toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: deep-soft/rust-cargo@master      
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: deep-soft/checkout@v3
      - uses: deep-soft/rust-toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: deep-soft/rust-cargo@master
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: deep-soft/checkout@v3
      - uses: deep-soft/rust-toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: deep-soft/rust-cargo@master
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: deep-soft/checkout@v3
      - uses: deep-soft/rust-toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: deep-soft/rust-cargo@master
        with:
          command: clippy
          args: -- -D warnings
